theme = "slick"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "pacman"
interval = 10

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
