#!/bin/sh

#------------------------------------------------------------------------------
# Globals:
#------------------------------------------------------------------------------

readonly BASEDIR="/etc/.dotfiles/rootfs"
readonly FILES="$(find ${BASEDIR} -type f | cut -b 23-)"
readonly C_CLEAR=$(tput sgr0)
readonly C_MAIN=${C_CLEAR}$(tput bold)
readonly C_OTHER=${C_MAIN}$(tput setaf 4)
readonly C_BUSY=${C_CLEAR}$(tput setaf 6)
readonly DEL_TEXT="\e[$(( $(( $(tput cols) - 13 )) + 4 ))G"

#------------------------------------------------------------------------------
# Helper functions:
#------------------------------------------------------------------------------

function stat_busy() {
  printf "${C_OTHER}:: ${C_MAIN}${1}${C_CLEAR} "
  printf "\e[s"
  printf "${DEL_TEXT}"
  printf "   ${C_OTHER}[${C_BUSY}BUSY${C_OTHER}]${C_CLEAR} "
}

function stat_done() {
  printf "${DEL_TEXT}"
  printf "   ${C_OTHER}[${C_MAIN}DONE${C_OTHER}]${C_CLEAR} \n"
}

#------------------------------------------------------------------------------
# Functions:
#------------------------------------------------------------------------------

function exists() {
  stat_busy $1; [ -f "$1" ] && return 0 || return 1
}

function hardlinked() {
  [ "$(stat -c %i $1)" == "$(stat -c %i $2)" ] && (stat_done; return 0) || return 1
}

function equal() {
  [ "$(md5sum $1 | awk '{print $1}')" == "$(md5sum $2 | awk '{print $1}')" ] && (stat_done; return 0) || return 1
}

function backup() {
  cp $1 $1.origin
}

function couple() {
  mkdir -p $(dirname $1)
  cp -alf $2 $1 2> /dev/null || cp -f $2 $1
  stat_done
}

#------------------------------------------------------------------------------
# Main loop:
#------------------------------------------------------------------------------

IFS=$'\n'; for i in ${FILES}; do

  SRC="/${i}"
  DST="${BASEDIR}/${i}"

  if exists ${SRC}; then
    hardlinked ${SRC} ${DST} && continue
    equal ${SRC} ${DST} && continue
    backup ${SRC}
  fi

  couple ${SRC} ${DST}

done

#------------------------------------------------------------------------------
# Set ownership:
#------------------------------------------------------------------------------

[ -d /home/marc ] && chown -R marc:users /home/marc
